### ISSUE TITLE
内源不错，但是阻力重重

### ISSUE THREAD

**Issue by coolbeevip** [phodal/innersource#2]
* 如何选择一个合适的项目开展内源
* 组织内部大部分项目没有有效的质量控制手段，没有产品自信，开放后会越来越乱（我觉得这是主要阻力）
* 组织内部现有项目缺少有效的内源角色

**Comment by phodal** [comment]
取决于内源是不是真正的自上而下，以及必要的决心。如果是自**上**而下，很多问题就很简单了。成立 PMO 等。

**Comment by coolbeevip** [comment]
> 取决于内源是不是真正的自上而下，以及必要的决心。如果是自**上**而下，很多问题就很简单了。成立 PMO 等。

自上而下想都不敢想，部门墙和内部竞争，往往导致决策者会首先成为**自下而上**的阻力。

感觉自下而上反倒是更容易成功一些 ：）

**Comment by phodal** [comment]
从我们在很多公司的咨询经验来看，**自上而下**只会在中小型公司成功，取决于领导的魄力。

自下而上在内源这一件事更不可能了，在组织层面完全不可能有人支持。自下而上容易成功的是开源，以外逼内。

**Comment by coolbeevip** [comment]
> 从我们在很多公司的咨询经验来看，**自上而下**只会在中小型公司成功，取决于领导的魄力。
> 
> 自下而上在内源这一件事更不可能了，在组织层面完全不可能有人支持。自下而上容易成功的是开源，以外逼内。

这确实是现状，自下而上很难跨过部门墙，即使比较成功也难免走向 fork 分裂
